version: "3"
services:
 app:
  build: ./app
  ports:
   - 1234:1234
  env_file:
  - ./app/.env
  volumes:
    - ./app:/app

 web:
  build: ./nginx
  ports:
   - 80:80
   - 443:443
  depends_on:
   - app
 rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    restart: on-failure

 database:
   image: postgres:latest
   environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: mysecretpassword
     POSTGRES_DB: mydb
   volumes:
     - postgres_volume:/var/lib/postgresql/data
   restart: always

volumes:
  postgres_volume: