version: "3"
services:
 app:
  build: ./app
  ports:
   - 1234:1234
  env_file:
  - ./app/.env
  volumes:
    - ./app:/app

 web:
  image: nginx:latest
  restart: unless-stopped
  ports:
   - 80:80
  depends_on:
   - app
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
 rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    restart: on-failure

 database:
   image: postgres:latest
   environment:
     POSTGRES_USER: user
     POSTGRES_PASSWORD: pass
     POSTGRES_DB: db
   volumes:
     - postgres_volume:/var/lib/postgresql/data
   restart: always

volumes:
  postgres_volume: